name: CI Pipeline

on:
  push:
    branches:
      - test-branch
  pull_request:
    branches:
      - test-branch

jobs:
  test:
    name: Set Up and Run Python Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

  deploy:
    name: Push Changes To Main Branch
    runs-on: ubuntu-latest
    needs: test
    if: success() # Only runs if tests are successful

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git configuration
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout main branch
        run: git checkout main

      - name: Merge test-branch into main
        run: |
          git fetch origin
          git checkout main
          git merge origin/test-branch --no-commit --no-ff || (echo "Merge conflicts detected" && exit 1) # Handle merge conflicts if any

      - name: Push changes to main
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
